import('/home/attila/.hermes/hermes-agent/node_modules/playwright/index.mjs').then(async ({ chromium }) => {
  const BASE = 'https://dentalvibe.vercel.app'
  const OUT = process.env.OUT || '/home/attila/Documents/Projects/dentalvibe/screenshots'
  const b = await chromium.launch()
  const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2 })
  const pg = await ctx.newPage()
  const shot = (n) => pg.screenshot({ path: `${OUT}/${n}.png` })
  const login = async (email) => {
    await pg.evaluate(() => { localStorage.clear(); sessionStorage.clear() })
    await pg.goto(BASE + '/login', { waitUntil: 'networkidle' })
    await pg.getByLabel('Email address').fill(email)
    await pg.getByLabel('Password').fill('password123')
    await pg.locator('form button:has-text("Sign In")').last().click()
    await pg.waitForTimeout(3000)
  }

  // patient: register wizard (p32/55)
  await pg.goto(BASE, { waitUntil: 'networkidle' })
  await shot('00-login')
  await pg.locator('button:has-text("Register")').click()
  await pg.waitForTimeout(400)
  await pg.getByLabel('First name').fill('Maria')
  await pg.getByLabel('Last name').fill('Santos')
  await pg.getByLabel('Birthdate').fill('1990-05-05')
  await pg.locator('button:text-is("Male")').click()
  await shot('01-register-wizard-step1')
  await pg.locator('button:has-text("Next")').click()
  await pg.getByLabel('Emergency contact').fill('Juan Santos · +63 917 555 0000')
  await pg.locator('button:has-text("Next")').click()
  await pg.getByLabel('Email address').last().fill('demo@x.ph')
  await pg.getByLabel('Password').last().fill('Wizard1')
  await shot('02-register-step3-rules')

  await login('maria@dentalvibe.ph')
  await shot('03-patient-home')
  await pg.goto(BASE + '/book', { waitUntil: 'networkidle' }); await pg.waitForTimeout(1200)
  await shot('04-book')
  await pg.locator('input[type="date"]').fill(new Date(Date.now() + 5 * 864e5).toISOString().slice(0, 10))
  await pg.waitForTimeout(800)
  await shot('04b-book-time-slots')
  await pg.goto(BASE + '/appointments', { waitUntil: 'networkidle' }); await pg.waitForTimeout(1200)
  await shot('05-my-appointments')
  await pg.goto(BASE + '/profile', { waitUntil: 'networkidle' }); await pg.waitForTimeout(1200)
  await shot('06-profile-visit-history')
  await pg.goto(BASE + '/notifications', { waitUntil: 'networkidle' }); await pg.waitForTimeout(1000)
  await shot('07-notifications')
  await pg.goto(BASE + '/security', { waitUntil: 'networkidle' }); await pg.waitForTimeout(800)
  await shot('08-account-security')

  // doctor: welcome (p48) + main
  await pg.evaluate(() => { localStorage.clear(); sessionStorage.clear() })
  await pg.goto(BASE + '/login', { waitUntil: 'networkidle' })
  await pg.getByLabel('Email address').fill('doctor@dentalvibe.ph')
  await pg.getByLabel('Password').fill('password123')
  await pg.locator('form button:has-text("Sign In")').last().click()
  await pg.waitForTimeout(2500)
  await shot('09-dentist-welcome')
  await pg.getByRole('button', { name: 'Continue' }).click().catch(() => {})
  await pg.waitForTimeout(600)
  await shot('10-doctor-home')
  await pg.goto(BASE + '/doctor/calendar', { waitUntil: 'networkidle' }); await pg.waitForTimeout(1500)
  await shot('11-calendar')
  await pg.goto(BASE + '/doctor/messages', { waitUntil: 'networkidle' }); await pg.waitForTimeout(1500)
  await shot('12-doctor-messages')
  await pg.goto(BASE + '/doctor/patients', { waitUntil: 'networkidle' }); await pg.waitForTimeout(1200)
  await shot('14-doctor-patients')

  // owner
  await login('owner@dentalvibe.ph')
  await shot('15-owner-home')
  await pg.goto(BASE + '/owner/income', { waitUntil: 'networkidle' }); await pg.waitForTimeout(1200)
  await shot('16-income-analytics')
  await pg.goto(BASE + '/owner/manage', { waitUntil: 'networkidle' }); await pg.waitForTimeout(1200)
  await shot('17-manage')
  await pg.goto(BASE + '/owner/staff', { waitUntil: 'networkidle' }); await pg.waitForTimeout(1200)
  await shot('18-staff')
  // dentist record (p67)
  await pg.getByRole('button', { name: /Dr\. Dulce Amor R\. Joson/ }).first().click()
  await pg.waitForTimeout(1500)
  await shot('19-dentist-record')
  await pg.goto(BASE + '/owner/settings', { waitUntil: 'networkidle' }); await pg.waitForTimeout(1200)
  await shot('20-settings-persist')
  // EHR + edit modal (p82)
  await pg.goto(BASE + '/owner/patients', { waitUntil: 'networkidle' }); await pg.waitForTimeout(1200)
  await pg.getByRole('button', { name: /Maria Santos/ }).first().click()
  await pg.waitForTimeout(1500)
  await shot('21-ehr-record')
  await pg.locator('[aria-label="Edit patient info"]').click().catch(() => {})
  await pg.waitForTimeout(600)
  await shot('22-edit-patient-modal')

  console.log('shots done')
  await b.close()
})
